### ISSUE TITLE
Tooltip with exact date and time missing on "# timeAgo" in posts

### ISSUE THREAD

**Issue by karanssu** [brockenbrough/ssu-social-frontend#109]
Description: On the Discover page, all posts display a "# timeAgo" timestamp in the top-right corner. However, there is no exact date and time shown anywhere on the post. The exact date and time should appear as a tooltip when the user hovers over the "# timeAgo" timestamp.

Steps to Reproduce:
1. Log in to the application.
2. Navigate to the Discover page.
3. Hover over the "# timeAgo" timestamp on any post.
4. Observe that no tooltip with the exact date and time appears.

Expected Behavior:
When hovering over the "# timeAgo" timestamp, a tooltip should display the exact date and time of the post.

Actual Behavior:
The "# timeAgo" timestamp does not show the exact date and time, and no tooltip appears when hovering over it.

**Comment by alramirez729** [comment]
https://github.com/brockenbrough/ssu-social-frontend/commit/e0537546a75b453b9b2a0cdf8b1587366e3d41b7
