### ISSUE TITLE
Long bio extends the page and replaces character with stars 

### ISSUE THREAD

**Issue by jacobburk** [brockenbrough/ssu-social-frontend#119]
Go to your profile 
click edit bio 
type in a very long bio that is under the character limit 
the page will have a scroll wheel at the bottom and the bio will extend off the page all the characters will be replaced with stars 
bio shouldn't go past the end of the page and be in the bio section

**Comment by Gobogabbl** [comment]
https://github.com/brockenbrough/ssu-social-frontend/commit/7e46ba79af7b713125b63d58340649f5ec542ad7

Fixed it, bios will now properly align themselves as to not extend the page
