### ISSUE TITLE
Expanding the Post (Clicking on it)

### ISSUE THREAD

**Issue by Gobogabbl** [brockenbrough/ssu-social-frontend#12]
When you expand a post, if there is an image in the post the image will now show.

**Comment by karanssu** [comment]
Issue Solved, The Image is displayed in the comment pop-up.

GitHub Link: https://github.com/brockenbrough/ssu-social-frontend/commit/9ce498f4a99a9b6be9b2b5337d97d3613aac7e5c

**Comment by karanssu** [comment]
Issue Solved, The Image is displayed in the comment pop-up.

GitHub Link: https://github.com/brockenbrough/ssu-social-frontend/commit/9ce498f4a99a9b6be9b2b5337d97d3613aac7e5c
