### ISSUE TITLE
Chat has multiple buttons which have the same functionality

### ISSUE THREAD

**Issue by SpencerSum111** [brockenbrough/ssu-social-frontend#126]
When you click on the chat button, there is a button with a notepad icon and one with a magnifying glass icon in the chat box. Both of these buttons seem to have the same functionalities, so why is there two buttons and not just a single button? I don't know if I'd entirely consider this a 'defect' as its not breaking anything, but it just feels unnecessary. Is one of the two buttons meant to be different in some way but isn't?

**Comment by karanssu** [comment]
After discussion in class we decided to keep both icons. So, it's not a bug.
