### ISSUE TITLE
Account Settings modal not working properly with dark mode

### ISSUE THREAD

**Issue by RaulG27** [brockenbrough/ssu-social-frontend#129]
How to find the bug:

- Navigate to the profile page in the SSUSocial app
- Click on the three dots in the top right corner
- Select "Account Settings"
- Observe the modal behavior when using dark mode

**Comment by alramirez729** [comment]
Fixed the dark/light mode of this component.

**Comment by alramirez729** [comment]
https://github.com/brockenbrough/ssu-social-frontend/commit/df4b40916fe2711917d5499b1b08f44ff0181d6f
