### ISSUE TITLE
Like button opens comment section

### ISSUE THREAD

**Issue by SpencerSum111** [brockenbrough/ssu-social-frontend#15]
When a user likes a post, the pop-up tab that shows post and its comments opens as well. That function should be exclusive to the comment button, and the like button should only update the like count when posts are liked/unliked.

**Comment by huthifa22** [comment]
Fixed by Huthifa: proof - https://github.com/brockenbrough/ssu-social-frontend/commit/fcabe510510a79487f13b16342a79f843d99eb7d
