### ISSUE TITLE
In progress indicator in wrong position

### ISSUE THREAD

**Issue by brockenbrough** [brockenbrough/ssu-social-frontend#25]
1. Go to private profile page.
2. Click For You.
3. There is no progress indicator during the delay waiting for the posts to appear.

This issue is the progress indicator is in the upper left corner under the navbar.  it should be moved to the center.

**Comment by karanssu** [comment]
Fixed: https://github.com/brockenbrough/ssu-social-frontend/commit/97cde5308de270a605b82d836e674bb4af8b7803
