### ISSUE TITLE
Comment entry is a single line.

### ISSUE THREAD

**Issue by brockenbrough** [brockenbrough/ssu-social-frontend#29]
1. Hit Discover.
2. Hit comment icon.
3. The pop up for entering a comment is a single line.  It should be a text area.  
4. Here is an example of how it is done in Twitter.
![image](https://github.com/user-attachments/assets/8d029c1e-cce1-43e7-a2be-d7b414389e36)

**Comment by Gobogabbl** [comment]
Assuming Huthifa fixed this but this is done Im pretty sure
