### ISSUE TITLE
Navbar covers up Follower/Following Page 

### ISSUE THREAD

**Issue by JoshRaimo** [brockenbrough/ssu-social-frontend#32]
Message stating user does not have any followers/not following anyone is partially cropped off by navbar.
Profile Tab - Click followers/following

View Issue Here:
https://github.com/user-attachments/assets/b11d923b-f24b-4186-8df8-d4eb5fe8cadc

**Comment by SpencerSum111** [comment]
The NavBar no longer covers up following/followers pages.
