### ISSUE TITLE
Light/Dark Mode post text issue

### ISSUE THREAD

**Issue by SpencerSum111** [brockenbrough/ssu-social-frontend#35]
Recreation steps:
1. Log in
2. View 'Discover' page
3. Switch between dark and light mode on page.

Screenshots of issue:
![Screenshot (1349)](https://github.com/user-attachments/assets/de477bca-58aa-4e3c-96c2-459ba99ec2d9)
![Screenshot (1350)](https://github.com/user-attachments/assets/f89da861-bc88-4ff5-b912-bc8f478b09dc)

**Comment by karanssu** [comment]
Fixed:  https://github.com/brockenbrough/ssu-social-frontend/commit/620ef66a0b351d18161932ba2f7478947713318f
