### ISSUE TITLE
some pages shouldn't be viewable when you're logged out

### ISSUE THREAD

**Issue by RaulG27** [brockenbrough/ssu-social-frontend#40]
recreation steps:
1. Make sure you're logged out
2. go to any of the navbar pages such as : https://ssu-social-app.onrender.com/privateUserProfile

if you try to go to a page such as the privateUserProfile and you're logged out then you should be redirected to the log in page

ideally if you're logged out you should only be able to see the log in, sign up and discover pages.

**Comment by JoshRaimo** [comment]
Fixed
