### ISSUE TITLE
For You Feed - does not include your posts.

### ISSUE THREAD

**Issue by brockenbrough** [brockenbrough/ssu-social-frontend#42]
The feed should include the currently logged in users posts.  This is in issue when you are in For You and you create a post.  You don't get to see the post you just created.  Ideally, the users posts would be included in the list.  Or if that is difficult, maybe it includes posts made by the user in the last 24 hours.

**Comment by SpencerSum111** [comment]
As mentioned in the "For You feed makes little sense" issue, a user's own posts now show in their For You feed.
