### ISSUE TITLE
Comment Submit Error

### ISSUE THREAD

**Issue by seanpotter045** [brockenbrough/ssu-social-frontend#5]
After making a comment, it sends you to a random page that doesn’t have any feed or even the original post. It displays all the comments with the ability to edit or delete any comment, no matter who submitted the comment. It also doesn’t work with light/dark mode.

**Comment by huthifa22** [comment]
Fixed by Huthifa - proof: https://github.com/brockenbrough/ssu-social-frontend/commit/f5738171177627bd307a0ca425a3556bf4b6194a
