### ISSUE TITLE
Deleting a post requires refresh to go away

### ISSUE THREAD

**Issue by alramirez729** [brockenbrough/ssu-social-frontend#52]
How to recreate: 
1. Create a post
2. Click on the top right corner menu of that post
3. Edit Post
4. Delete
5. Post is there
6. Refresh
7. The post is gone

The post should be deleted from the Discover page as soon as it is gone without any refresh.

**Comment by SpencerSum111** [comment]
When you delete a post on the discover page, it gets deleted without having to refresh the page.

**Comment by SpencerSum111** [comment]
This works on the Discover page but not the For You page.

**Comment by SpencerSum111** [comment]
This same issue is also present on the 'For You' page. Both pages should have this functionality.
