### ISSUE TITLE
Clunky styling of post list in public profile

### ISSUE THREAD

**Issue by G10C** [brockenbrough/ssu-social-frontend#60]
If you click on comments, the window is blocked by the post next to it. works fine with the post mostly to the right.

**Comment by G10C** [comment]
If you click on comments, they are blocked by the next post to the left

**Comment by huthifa22** [comment]
This component has been changed by Haddy. 
When clicking on a post on public profile page it now has a pop-up list and each post has a comment section but it's vertical so this specific bug doesn't occur anymore.
