### ISSUE TITLE
Text Censoring Messing Up Youtube Links

### ISSUE THREAD

**Issue by Gobogabbl** [brockenbrough/ssu-social-frontend#68]
If you post a youtube link and that link gets censored then the thumbnail will not pop up and the link will no longer take you to the intended video.

1. Create Post
2. Copy paste a Youtube link
3. If the link is censored, click on the link
4. This should send you to youtube homepage rather than the intended video
![Screen Shot 2024-11-14 at 11 52 12 AM](https://github.com/user-attachments/assets/977f7be7-cd22-4946-b28f-8bd147486084)

**Comment by Gobogabbl** [comment]
https://www.youtube.com/watch?v=zH-hdtqeaZI

This is the link that I attempted to use

**Comment by Grummps** [comment]
Should be fixed when we upgraded to gpt-4-turbo:

https://github.com/brockenbrough/ssu-social-backend/commit/63623ff29a1cdfa5440ad59ffeae4dd293fe8d19
