### ISSUE TITLE
Log in Info Error

### ISSUE THREAD

**Issue by seanpotter045** [brockenbrough/ssu-social-frontend#7]
When giving an incorrect info on the log in page, it has the web browser send this error message: Error: [object Object] 401 https://ssu-social-app-api.onrender.com/user/login

It also has the page send this message: Something went wrong. Please try again.

This doesn’t help the user understand what’s wrong, like if their username, password, or both are wrong.

**Comment by brockenbrough** [comment]
We paid for render.
