### ISSUE TITLE
There is not check on username length

### ISSUE THREAD

**Issue by brockenbrough** [brockenbrough/ssu-social-frontend#71]
You can create very large user names in the system.  We should limit user names to 28 characters or less.

Tests:
1. Create a new user
2.  Try to enter a 29 character username.
3.  You should get a message saying the user name is limited to 16 characters.

**Comment by SpencerSum111** [comment]
Changes to be made:
1. When user enters invalid information, remove the original message and only show the error under the problematic information.
2. Give usernames an upper bound of 28, implement error message for when username > 28 characters.
3. Change color of error messages to lighter shade of red
