### ISSUE TITLE
Creating a post is slow and needs an indication that it is in progress.

### ISSUE THREAD

**Issue by brockenbrough** [brockenbrough/ssu-social-frontend#73]
Test
1. Go to Discover.
2. Hit enter the post information and hit the Create button.
3. There is a delay before the post is created, but the cursor does not change.  This makes the user think that maybe they should hit the Create button again.  Instead, change the cursor to an hourglass and change back to pointer when done (or something similar).

**Comment by karanssu** [comment]
Fixed: https://github.com/brockenbrough/ssu-social-frontend/commit/3aff8ea782f4498a99ba7ea5642318b5a9b603a9
