### ISSUE TITLE
Web Socket for Comments not fully working 

### ISSUE THREAD

**Issue by huthifa22** [brockenbrough/ssu-social-frontend#76]
The comment section currently has web sockets but it's not working 100%. It will only pull other people's comments when the current user makes a new comment or they open and reopen the comment section.

To Test
- Open a comment section and make a comment
- Have another user make a comment while this comment section is open
- The initial user wont receive this comment unless they make another comment or they close and reopen that same comment section

**Comment by karanssu** [comment]
Fixed: https://github.com/brockenbrough/ssu-social-frontend/commit/72809beb588c8187badfb6b0c8534a304ea68912
