### ISSUE TITLE
Clicking on your own username when in discover tab will bring you to your public profile page, where you can see "edit profile"

### ISSUE THREAD

**Issue by Grummps** [brockenbrough/ssu-social-frontend#77]
Step 1: Login
Step 2: Make a post
Step 3: Go to discover
Step 4: Click on your username
Step 5: You'll be directed to your public profile page
Step 6: Notice the "edit profile" button and not the "edit bio" button

**Comment by alramirez729** [comment]
https://github.com/brockenbrough/ssu-social-frontend/commit/eb64285f437fb3b419fd2da284746e8afb08eebb
