### ISSUE TITLE
View likes "No likes yet" text is invisible in dark mode

### ISSUE THREAD

**Issue by G10C** [brockenbrough/ssu-social-frontend#82]
Steps to find the defect:
1. Login and switch to dark mode
2. Find a post with no likes on the Discover page and click "View likes"

**Comment by Gobogabbl** [comment]
https://github.com/brockenbrough/ssu-social-frontend/commit/79d5d0f1e04c8215e352811fe77e9aafe2f2d3d0

Fixed the issue and made the texts and background more dynamic for the View Likes section
