### ISSUE TITLE
Signup Page Error messages are displayed prematurely

### ISSUE THREAD

**Issue by karanssu** [brockenbrough/ssu-social-frontend#84]
Description: On the signup page, error messages are shown under each input box in gray color as soon as the page loads. These error messages should only appear when the signup button is clicked, and only for the invalid fields.

Steps to Reproduce: 
1. Navigate to the signup page.
2. Observe that error messages appear under each input field without any user interaction.

Expected Behavior:
- Error messages should not be visible until the signup button is clicked.
- Only the relevant error message should appear under the corresponding invalid input field.

Actual Behavior:
Error messages are displayed under all input fields in gray color as soon as the page loads, even without clicking the signup button.

**Comment by SpencerSum111** [comment]
Fixed as a part of #71
