### ISSUE TITLE
Signup Page Background images overlap and display incorrectly

### ISSUE THREAD

**Issue by karanssu** [brockenbrough/ssu-social-frontend#95]
Description: The signup page displays two background images simultaneously, one covering 70% of the width and the other 30%, which makes the layout look broken. Additionally, sometimes a broken image results in a black background. Only one image should be displayed at a time, changing periodically, and there should always be an image displayed.

Steps to Reproduce:
1. Navigate to the signup page.
2. Observe that two images overlap, with one covering 70% of the screen and the other 30%.
3. Wait for the images to change and note that sometimes a broken image results in a black background.

Expected Behavior:
- Only one background image should be displayed at a time, changing periodically.
- There should never be a black-colored background; a valid image should always be visible.

Actual Behavior:
- Two background images overlap, creating a broken appearance.
- Occasionally, a black-colored background appears due to a missing or broken image.

**Comment by JashATSSU** [comment]
https://github.com/brockenbrough/ssu-social-frontend/commit/1f7aafb5d3c576a3dc06a6d54173d5d4bc8bba59
