### ISSUE TITLE
Blue text in Private Profile's user Bio (Light Mode)

### ISSUE THREAD

**Issue by G10C** [brockenbrough/ssu-social-frontend#96]
Steps to find it:
1. Make sure you're in Light Mode
2. Login and go to Profile
3. Click "edit bio", enter a new biography, and submit it

**Comment by karanssu** [comment]
Fixed: https://github.com/brockenbrough/ssu-social-frontend/commit/8d07e47575b1610a23243a3480eab6ecc2607e60
